server:
    port: ${GATE_PORT}

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: ${EUREKA_URL}

spring:
    application:
        name: gateway-service

    cloud:
        gateway:
            globalcors:
                add-to-simple-url-handler-mapping: true
                corsConfigurations:
                    '[/**]':
                        allowedOriginPatterns: ${ALLOW_ORIGIN}
                        allow-credentials: true
                        allowedHeaders: ${ALLOW_HEADER}
                        exposedHeaders: ${EXPOSE_CREDENT}
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
            routes:
                - id: farm-service
                  uri: lb://FARM-SERVICE
                  predicates:
                      - Path=/api/farm-service/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=${REWRITE_FARM}

                - id: sse-service
                  uri: lb://SSE-SERVICE
                  predicates:
                      - Path=/api/connection/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=${REWRITE_SSE}

                - id: state-service
                  uri: lb://STATE-SERVICE
                  predicates:
                      - Path=/api/state-service/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=${REWRITE_STATE}

                - id: line-service
                  uri: lb:LINE-SERVICE
                  predicates:
                      - Path=/api/line-service/**
                  filters:
                      - RemoveRequestHeader=Cookie
                      - RewritePath=${REWRITE_LINE}
